import Head from "next/head";
import Image from "next/image";
import "tailwindcss/tailwind.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={
          "flex flex-col min-h-screen content-between justify-between items-center bg-gradient-to-br from-red-50 to-blue-50"
        }
      >
        <main className="flex-grow pb-64">
          <div className=" flex justify-center pt-48 pb-32">
            <div>
              <h1 className="text-6xl font-bold tracking-tight">
                You know what’s c
                <span className="transition-colors relative group hover:text-white">
                  o
                  <a
                    href="#"
                    className="transition-colors group-hover:text-red-500 rounded-full text-white absolute text-xs text-right pr-1 leading-3 top-6 left-0.5 h-9 w-9"
                  >
                    yk
                    <br />
                    wc
                    <br />
                    .dev
                  </a>
                </span>
                ol?
              </h1>

              <div className="font-bold">
                <p className="text-justify pl-16 relative">
                  {"y k w c "}
                  <a
                    href="#"
                    className="text-right right-0 absolute opacity-0 hover:opacity-100 transition-opacity hover:text-red-500"
                  >
                    ykwc.dev
                  </a>
                  .dev
                  <span className="w-full inline-block" aria-hidden />
                </p>
              </div>
            </div>
          </div>

          <div className="text-xl grid grid-cols-1 gap-1 py-24">
            <p>
              <span className="bg-black text-white font-bold pt-9 pl-6 pb-1 pr-1">
                cool
              </span>{" "}
              is tech that makes sense,
            </p>
            <p>
              <span className="font-bold pt-8 pl-6 pb-1 ">cool</span> is easy to
              work with, easy to use, and
            </p>
            <p>
              <span className="font-bold pt-8 pl-6 pb-1 ">cool</span> is simple.
            </p>
          </div>

          <div className="text-xl flex justify-center py-24">
            <p>
              <span className="ring-black ring-4 py-4 px-2 font-bold mr-3">
                your idea is cool,
              </span>{" "}
              let's make it happen.
            </p>
          </div>
        </main>

        <footer className="bg-white py-20 w-full pl-8">
          <p className="font-bold text-xl tracking-wider">ykwc.dev</p>
          <p className="text-xs">
            © 2021 YOU KNOW WHAT'S COOL?, All Rights Reserved
          </p>
        </footer>
      </div>
    </>
  );
}
